In [1]:
import numpy as np
import torch

Eigenvectors and Eigenvalues

Eigenvectors are special vectors that does not change direction of the original vector when a matrix transformation is applied to the vector

Eigenvalue the the scaler quatity by which the original vector the changed i.e. streched or shinked

$$
A \mathbf{v} = \lambda \mathbf{v}
$$


In [2]:
A = np.array([[1, 2], [2, -1]])
v = np.array([1, 4])

In [4]:
eigValue, eigVector = np.linalg.eig(A)

In [11]:
# EigenVector
eigVector 

array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]])

In [8]:
# EigenValue
eigValue

array([ 2.23606798, -2.23606798])

In [24]:
np.dot(A,eigVector[:,0])

array([1.90211303, 1.1755705 ])

In [25]:
np.dot(eigValue[0], eigVector[:, 0])

array([1.90211303, 1.1755705 ])

In [26]:
np.dot(A, eigVector[:, 1])

array([ 1.1755705 , -1.90211303])

In [27]:
np.dot(eigValue[1], eigVector[:, 1])

array([ 1.1755705 , -1.90211303])