In [3]:
import torch as tc
import numpy as np

Numpy matrix multiplication of a matrix and vector

In [13]:
a_mat_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b_vec_numpy = np.array([10, 20, 30])

In [14]:
np.dot(a_mat_numpy, b_vec_numpy)

array([140, 320, 500])

PyTorch matrix multiplication of matrix and vector

In [15]:
a_mat_torch = tc.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b_vec_torch = tc.tensor([10, 20, 30])

In [16]:
tc.matmul(a_mat_torch, b_vec_torch)

tensor([140, 320, 500])

Numpy matrix multiplication of matrix and matrix

In [18]:
x_mat_numpy = np.array([[1, 2], [2, 3], [8, 9]])
y_mat_numpy = np.array([[3, 4], [8, 9]])

In [19]:
np.dot(x_mat_numpy, y_mat_numpy)

array([[ 19,  22],
       [ 30,  35],
       [ 96, 113]])

PyTorch matrix multiplication of matrix and matrix

In [20]:
x_mat_torch = tc.tensor([[1, 2], [2, 3], [8, 9]])
y_mat_torch = tc.tensor([[3, 4], [8, 9]])

In [21]:
tc.matmul(x_mat_torch, y_mat_torch)

tensor([[ 19,  22],
        [ 30,  35],
        [ 96, 113]])

Symmetric matrix and Identity matrix

Symmetric matrix :
    1. It should be square matrix
    2. The transpose of the matrix A should be equal to A $A^T == A$

In [4]:
A = np.array([[1, 2, 3], [2, 5, 6], [3, 6, 9]])
A_T = A.T

In [5]:
A == A_T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Identity Matrix : 
    1. All the diagonal elements are 1
    2 Rest all elements are zeros $I_3$

In [6]:
A_Identity = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [7]:
A_Identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Matrix Inversion

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

$$
A^{-1} =
\frac{1}{ad - bc}
\begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}
$$


$$
A^{-1} =
\begin{bmatrix}
-2 & 1 \\
1.5 & -0.5
\end{bmatrix}
$$

In [8]:
A = np.array([[1, 2], [3, 4]])

In [9]:
A_INV = np.linalg.inv(A)

In [10]:
A_INV

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Matrix inversion using PyTorch

In [13]:
A = tc.tensor([[1, 2], [3, 4.]])
A_INV = tc.linalg.inv(A)

A_INV

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

Diagonal Matrix

$$
B =
\begin{bmatrix}
3 & 0 & 0 \\
0 & 5 & 0 \\
0 & 0 & 7
\end{bmatrix}
$$

Diagonal matrix - inversion property

$$
D^{-1} =
\begin{bmatrix}
\frac{1}{d_1} & 0 & 0 \\
0 & \frac{1}{d_2} & 0 \\
0 & 0 & \frac{1}{d_3}
\end{bmatrix}
$$

In [15]:
B = np.array([[3, 0, 0], [0, 5, 0], [0, 0 ,7]])
B

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])