In [28]:
import numpy as np
import torch

Eigenvectors and Eigenvalues

Eigenvectors are special vectors that does not change direction of the original vector when a matrix transformation is applied to the vector

Eigenvalue the the scaler quatity by which the original vector the changed i.e. streched or shinked

$$
A \mathbf{v} = \lambda \mathbf{v}
$$


In [2]:
A = np.array([[1, 2], [2, -1]])
v = np.array([1, 4])

In [4]:
eigValue, eigVector = np.linalg.eig(A)

In [11]:
# EigenVector
eigVector 

array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]])

In [8]:
# EigenValue
eigValue

array([ 2.23606798, -2.23606798])

In [24]:
np.dot(A,eigVector[:,0])

array([1.90211303, 1.1755705 ])

In [25]:
np.dot(eigValue[0], eigVector[:, 0])

array([1.90211303, 1.1755705 ])

In [26]:
np.dot(A, eigVector[:, 1])

array([ 1.1755705 , -1.90211303])

In [53]:
eigValue[1] * eigVector[:, 1]

array([ 1.1755705 , -1.90211303])

Eigenvectors and eigenvalues using PyTorch

In [29]:
AT = torch.tensor([[1, 2], [2, -1.]])

In [45]:
eigenvalues_torch, eigenvectors_torch = torch.linalg.eigh(AT)

In [46]:
torch.matmul(AT, eigenvectors_torch[:, 0])

tensor([-1.1756,  1.9021])

In [52]:
eigenvalues_torch[0] * eigenvectors_torch[:, 0]

tensor([-1.1756,  1.9021])

3D Matrix - Eigenvectors and eigenvalues using PyTorch

In [65]:
X = torch.tensor([[1, 2, 3], [9, 7, 7], [5, 7, 1.]])

In [74]:
lx, xv = torch.linalg.eig(X)
lx = lx.real
xv = xv.real

In [75]:
print(torch.matmul(X, xv[:, 0]))
print(lx[0] * xv[:, 0])

tensor([ -3.4495, -11.5726,  -7.4499])
tensor([ -3.4495, -11.5726,  -7.4499])


In [76]:
print(torch.matmul(X, xv[:, 1]))
print(lx[1] * xv[:, 1])

tensor([ 1.6535, -0.4936, -1.4724])
tensor([ 1.6535, -0.4936, -1.4724])
