In [11]:
import torch as tc
import numpy as np

Numpy matrix multiplication of a matrix and vector

In [13]:
a_mat_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b_vec_numpy = np.array([10, 20, 30])

In [14]:
np.dot(a_mat_numpy, b_vec_numpy)

array([140, 320, 500])

PyTorch matrix multiplication of matrix and vector

In [15]:
a_mat_torch = tc.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b_vec_torch = tc.tensor([10, 20, 30])

In [16]:
tc.matmul(a_mat_torch, b_vec_torch)

tensor([140, 320, 500])

Numpy matrix multiplication of matrix and matrix

In [18]:
x_mat_numpy = np.array([[1, 2], [2, 3], [8, 9]])
y_mat_numpy = np.array([[3, 4], [8, 9]])

In [19]:
np.dot(x_mat_numpy, y_mat_numpy)

array([[ 19,  22],
       [ 30,  35],
       [ 96, 113]])

PyTorch matrix multiplication of matrix and matrix

In [20]:
x_mat_torch = tc.tensor([[1, 2], [2, 3], [8, 9]])
y_mat_torch = tc.tensor([[3, 4], [8, 9]])

In [21]:
tc.matmul(x_mat_torch, y_mat_torch)

tensor([[ 19,  22],
        [ 30,  35],
        [ 96, 113]])