In [28]:
import numpy as np
import torch

Eigenvectors and Eigenvalues

Eigenvectors are special vectors that does not change direction of the original vector when a matrix transformation is applied to the vector

Eigenvalue the the scaler quatity by which the original vector the changed i.e. streched or shinked

$$
A \mathbf{v} = \lambda \mathbf{v}
$$


In [2]:
A = np.array([[1, 2], [2, -1]])
v = np.array([1, 4])

In [4]:
eigValue, eigVector = np.linalg.eig(A)

In [11]:
# EigenVector
eigVector 

array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]])

In [8]:
# EigenValue
eigValue

array([ 2.23606798, -2.23606798])

In [24]:
np.dot(A,eigVector[:,0])

array([1.90211303, 1.1755705 ])

In [25]:
np.dot(eigValue[0], eigVector[:, 0])

array([1.90211303, 1.1755705 ])

In [26]:
np.dot(A, eigVector[:, 1])

array([ 1.1755705 , -1.90211303])

In [53]:
eigValue[1] * eigVector[:, 1]

array([ 1.1755705 , -1.90211303])

Eigenvectors and eigenvalues using PyTorch

In [29]:
AT = torch.tensor([[1, 2], [2, -1.]])

In [45]:
eigenvalues_torch, eigenvectors_torch = torch.linalg.eigh(AT)

In [46]:
torch.matmul(AT, eigenvectors_torch[:, 0])

tensor([-1.1756,  1.9021])

In [52]:
eigenvalues_torch[0] * eigenvectors_torch[:, 0]

tensor([-1.1756,  1.9021])

3D Matrix - Eigenvectors and eigenvalues using PyTorch

In [65]:
X = torch.tensor([[1, 2, 3], [9, 7, 7], [5, 7, 1.]])

In [74]:
lx, xv = torch.linalg.eig(X)
lx = lx.real
xv = xv.real

In [75]:
print(torch.matmul(X, xv[:, 0]))
print(lx[0] * xv[:, 0])

tensor([ -3.4495, -11.5726,  -7.4499])
tensor([ -3.4495, -11.5726,  -7.4499])


In [76]:
print(torch.matmul(X, xv[:, 1]))
print(lx[1] * xv[:, 1])

tensor([ 1.6535, -0.4936, -1.4724])
tensor([ 1.6535, -0.4936, -1.4724])


Eigendecomposition

In [78]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [87]:
PL, PV = torch.linalg.eig(P)
PL = PL.real
PV = PV.real

In [93]:
torch.matmul(PV, torch.matmul(torch.diag(PL), torch.linalg.inv(PV)))

tensor([[25.0000,  2.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])

Eigendecomposition of singular matrix

In [103]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [100]:
SL, SV = torch.linalg.eig(S)
SL = SL.real
SV = SV.real

In [101]:
torch.matmul(SV, torch.matmul(torch.diag(SL), SV.T))

tensor([[25.0000,  2.0000, -5.0000],
        [ 2.0000, -2.0000,  1.0000],
        [-5.0000,  1.0000,  4.0000]])

Determinant of a matrix - a scaler value that describe a matrix
Product of all eigenvalues == determinant of the matrix

In [108]:
print(torch.linalg.det(P))
print(torch.prod(PL))

tensor(-543.9999)
tensor(-543.9998)


In [110]:
print(torch.linalg.det(S))
print(torch.prod(SL))

tensor(-211.0000)
tensor(-211.0000)
