**Single value decomposition**
<br>
<br>
Similar to eigenvalue decomposition but where eigenvalue decomposition works in square matrix (n x n), SVD words in rectangle matrix (m x n).
<br>
Singular vector -> Eigenvector <br>
Singular value -> Eigenvalue <br>

$$
    A = UDV^T
$$

<br>

U -> Left singular matrix (m x m) <br>
D -> Singular value <br>
V -> Right singular matrix (n * n) <br>

In [1]:
import numpy as np
import torch

In [3]:
P = torch.tensor([[1, 2], [3, 4], [5, 6.]])

In [5]:
U, D, V = torch.linalg.svd(P)

In [6]:
print(U)
print(D)
print(V)

tensor([[-0.2298,  0.8835,  0.4082],
        [-0.5247,  0.2408, -0.8165],
        [-0.8196, -0.4019,  0.4082]])
tensor([9.5255, 0.5143])
tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])


In [ ]:
PP = torch.linalg.pinv(P)

tensor([[-1.3333, -0.3333,  0.6667],
        [ 1.0833,  0.3333, -0.4167]])

**Trace Operator**
<br>

Sum of all diagonal elements of the matrix<br>
Sum of all eigenvalues

In [8]:
B = torch.tensor([[1, 2], [3, 4.]])

In [9]:
torch.trace(B)

tensor(5.)

In [10]:
l, v = torch.linalg.eig(B)

In [14]:
torch.sum(l).real

tensor(5.0000)